### PR TITLE
Add metadata / contentType getters and setters

### PR DESCRIPTION
**Pull request by squio**
Ref issue #16 add these missing methods. Copied literally from `PutCommand.php` - there might be a better way but this seems to work just fine.

### CODE REVIEW

**Comment by frostealth** [comment]
Hello.
There are no missing methods. 

`PutCommand` and `UploadCommand` are a little different.
The `UploadCommand` is used to upload a file with its metadata to S3 by path or stream.

If these commands were identical, there would be only one command to upload the data.

Have you got some problems with uploading files using this command?

**Comment by squio** [comment]
I want to achieve the same result as with version 1.0 - that is: specify ContentType and extra metadata for a uploaded file using the upload command.

Code snippet using yii2-aws-s3 v1.0 (this worked as intended):

```
        try {
            Yii::$app->get('s3bucket')->upload($pathname, $this->uploadfile->tempName, null, [
                'params' => [
                    'ContentType' => $mime,
                    'ContentDisposition' => 'attachment',
                ],
            ]);
```

Is there another way in v2.0 to achieve exactly this?

**Comment by frostealth** [comment]
No, there isn't. 
Unfortunately, this code doesn't work.

I understand you and I'll add `setParams()`, `setContentType()` and `setContentDisposition()` this morning.
Is it ok?

**Comment by squio** [comment]
Even better; I'll delete the pull request afterwards.

**Pull request closed without merging**
