### PR TITLE
List command by prefix

### PR DESCRIPTION
**Pull request by alessiodionisi**
Use `ListObjects`

Example:
`$result = $s3->commands()->list('/path')->execute();`

### CODE REVIEW

**Comment by chuprik** [comment]
What is this?

image

**Comment by alessiodionisi** [comment]
No idea, I use Atom as editor

**Comment by chuprik** [comment]
can you drop this changes? because this is trash

**Comment by alessiodionisi** [comment]
I think it's better, actually Atom has removed the empty spaces that are useless

**Comment by alessiodionisi** [comment]
Why is not merged?

**Comment by chuprik** [comment]
don't worry will be merged in shortly. just need to test this changes :)

**Comment by frostealth** [comment]
@alessiodionisi, @kotchuprik thanks!

**Pull request merged**
